### ISSUE TITLE
Need a new release to fix Python 3 compatibility

### ISSUE THREAD

**Issue by haypo** [mitsuhiko/babel#228] opened 2015-09-21 08:48 UTC
Hi,

The latest release Babel 2.0 doesn't work on Python 3 because of the bug #174. Good news: the pull request #188 already fixed the bug 11 days ago. The last point is to get a release on PyPI. I prefer to open a new issue because the previous bug report and the pull request are both closed.

This bug is blocking me to port the OpenStack Horizon project to Python 3.

@sils1297 wants to do the release, but he doesn't have access to PyPI. He wrote "we're still not having access to pypi to update that, it's a bit hard to reach the old maintainer. You can install Babel from git in the meantime: "

@mitsuhiko: can you please do the release or allow others to release a new version? Thanks.

Note: @sils1297 suggests to install Babel with @@https://pip.pypa.io/en/latest/reference/pip_install.html#git@@ until a new release is available.

**Comment by mitsuhiko** [comment] 2015-09-21 08:50
I can provide access to pypi to @sils1297 but I need his pypi name.

**Comment by haypo** [comment] 2015-09-21 10:01
> I can provide access to pypi to @sils1297 but I need his pypi name.

I replied on IRC: "sils". Armin allowed sils to upload to PyPI, congrats @sils1297, the new release manager :-D

**Comment by sils1297** [comment] 2015-09-21 10:21
@haypo @mitsuhiko thanks, closing this as a duplicate of https://github.com/mitsuhiko/babel/issues/224 .

@mitsuhiko could you please look into https://github.com/mitsuhiko/babel/issues/209 ? In there I'm proposing

- To move this repository to the https://github.com/python-babel organization so we can manage permissions and webhooks by ourselves, GitHub should automatically take care of forwarding.
- Giving the `babel` user on pypi permission to do the releases. `sils` is my personal user and as we are several maintainers and want to do automatic development releases, we'll want to have an own proxy user for that. I don't seem to have permissions to give other users permissions to do that.

**Closed by sils1297** 2015-09-21 10:21 UTC
