### ISSUE TITLE
Traceback in babel, when using it with Python 3.4 & Windows 10

### ISSUE THREAD

**Issue by ranvik14** [mitsuhiko/babel#205] opened 2015-08-22 14:16 UTC
I'd like to report the following issue

<Log>

Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. Alle Rechte vorbehalten.

PS C:\Users\Viktor> python --version
Python 3.4.3
PS C:\Users\Viktor> python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from babel import localtime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\babel\localtime\__init__.py", line 21, in <module>
    from babel.localtime._win32 import _get_localzone
  File "C:\Python34\lib\site-packages\babel\localtime\_win32.py", line 18, in <module>
    tz_names = get_global('windows_zone_mapping')
  File "C:\Python34\lib\site-packages\babel\core.py", line 58, in get_global
    _global_data = pickle.load(fileobj)
TypeError: an integer is required (got type str)
>>> quit()
PS C:\Users\Viktor>

</Log>

**Comment by ranvik14** [comment] 2015-08-22 14:27
For the background & context see: http://mail.scipy.org/pipermail/ipython-user/2015-August/013994.html
Credit for the analysis goes to Paul Moore.

**Comment by jun66j5** [comment] 2015-08-22 14:35
Duplicate of #174 and #175.

**Comment by sils1297** [comment] 2015-08-23 13:48
@erickwilder can you resolve the duplicates please? Mobile internet
connection in non home country makes this hard for me right now.

**Closed** 2015-08-24 16:36 UTC
Labels: duplicate
