### ISSUE TITLE
Exception occurs at unpickling global.dat

### ISSUE THREAD

**Issue by hans-boden** [mitsuhiko/babel#175] opened 2015-07-31 14:45 UTC
Hi,

I work on Windows7 from inside the git-bash command line. Babel came to me as a part of a sphinx upgrade. Whith this error, my sphinx is blocked. Starting sphinx produces the same error as below.

Right after a fresh install of Babel I type in the example statements from the Locale Page. This is what happens:

$ pip install babel
Downloading/unpacking babel
  Running setup.py (path:C:\Users\insehb1\AppData\Local\Temp\pip_build_insehb1\babel\setup.py) egg_info for package babe
l

    warning: no previously-included files matching '*' found under directory 'docs\_build'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
Requirement already satisfied (use --upgrade to upgrade): pytz>=0a in c:\python34\lib\site-packages (from babel)
Installing collected packages: babel
  Running setup.py install for babel

    warning: no previously-included files matching '*' found under directory 'docs\_build'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    Installing pybabel-script.py script to C:\Python34\Scripts
    Installing pybabel.exe script to C:\Python34\Scripts
Successfully installed babel
Cleaning up...

$ python
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:45:13) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from babel import Locale
>>> locale = Locale('en', 'US')
>>> locale.territories['US']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python34\lib\site-packages\babel\core.py", line 487, in territories
    return self._data['territories']
  File "c:\Python34\lib\site-packages\babel\core.py", line 345, in _data
    self.__data = localedata.LocaleDataDict(localedata.load(str(self)))
  File "c:\Python34\lib\site-packages\babel\localedata.py", line 89, in load
    data = load(parent).copy()
  File "c:\Python34\lib\site-packages\babel\localedata.py", line 89, in load
    data = load(parent).copy()
  File "c:\Python34\lib\site-packages\babel\localedata.py", line 96, in load
    data = pickle.load(fileobj)
  File "c:\Python34\lib\site-packages\babel\dates.py", line 28, in <module>
    from babel.util import UTC, LOCALTZ
  File "c:\Python34\lib\site-packages\babel\util.py", line 278, in <module>
    from babel import localtime
  File "c:\Python34\lib\site-packages\babel\localtime\__init__.py", line 21, in <module>
    from babel.localtime._win32 import _get_localzone
  File "c:\Python34\lib\site-packages\babel\localtime\_win32.py", line 18, in <module>
    tz_names = get_global('windows_zone_mapping')
  File "c:\Python34\lib\site-packages\babel\core.py", line 58, in get_global
    _global_data = pickle.load(fileobj)
TypeError: an integer is required (got type str)
>>>

Any recommendation, what to do? Thanks in advance and kind regards

Hans

**Comment by sils1297** [comment] 2015-07-31 15:13
probable duplicate of https://github.com/mitsuhiko/babel/issues/174

**Comment by sils1297** [comment] 2015-07-31 15:13
Thanks for reporting, we'll investigate that!

**Comment by erickwilder** [comment] 2015-07-31 17:17
I think that both #174 and this issue could be fixed by executing `clean-cldr` *before* `import-cldr` in the `release` task described at `Makefile`. It will ensure that no previous generated `.dat` files will be

**Comment by sils1297** [comment] 2015-07-31 17:35
@erickwilder why're you reopening a duplicate?

**Comment by erickwilder** [comment] 2015-07-31 17:35
@sils1297 
Yes, this is the same behaviour found at the report made in #174 
I'm trying to figure out how to solve this, any help is welcome.

**Closed by erickwilder** 2015-07-31 17:35 UTC
Labels: bug, duplicate

**Comment by erickwilder** [comment] 2015-07-31 17:36
No, I was just making a double check here before closing.
